baseURL: https://vrinda-gupta-blog.netlify.app/
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Welcome to Vrinda's blog!
    subtitle: UNDERSTANDING THE STARTING
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: SOUL FOOD FOR SIMPLISTS
  blog: {}
  contact:
    address:
      - city: London, NW16AY
        country: United Kingdom
        street: Glentworth Street
        title: Address
    buttonClear: Clear
    buttonSend: Tell me what you think!
    email:
      - email: vrindagupta66@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7760826659
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Vrinda's Blog
    enable: yes
    quicklinks:
      - alt: CLICK FOR FULL BLOG
        text: 'More like this: '
        url: https://www.vrindagupta66.wordpress.com
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/vrindagupta66/
      - icon: fa-wordpress
        label: Wordpress
        url: https://vrindagupta66.wordpress.com/
      #- icon: fa-instagram
       # label: Instagram
       # url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/vrindagupta66
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/vrindagupta66/
  image: 'IMG_4835'
  name: Vrinda Gupta
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
