baseURL: https://vrinda-gupta-blog.netlify.app/
languageCode: en-us
title: Portfolio website for Kostis Christodoulou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Welcome to Vrinda's blog!
    subtitle: UNDERSTANDING THE STARTING
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      ##
    title: SOUL FOOD FOR SIMPLISTS
  blog: {}
  contact:
    address:
      - city: London, NW16AY
        country: United Kingdom
        street: Glentworth Street
        title: Address
    buttonClear: Clear
    buttonSend: Tell me what you think!
    email:
      - email: vrindagupta66@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7760826659
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Vrinda's Blog
    enable: yes
    quicklinks:
      - alt: CLICK FOR FULL BLOG
        text: 'More like this: '
        url: https://www.vrindagupta66.wordpress.com
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/vrindagupta66/
      - icon: fa-wordpress
        label: Wordpress
        url: https://vrindagupta66.wordpress.com/
      #- icon: fa-instagram
       # label: Instagram
       # url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/vrindagupta66
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/vrindagupta66/
      - image: pic02
  name: Vrinda Gupta
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: 'https://app.netlify.com/login/email'
    links:
      - name: Home
        url: 'https://vrinda-gupta-blog.netlify.app/'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
     # - name: Elements
      #  url: elements.html
    menu: Menu
    subtitle: By Vrinda Gupta
    title: Creative Nonfiction
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Analysing Top 30 Stock Returns
        title: R Work 1 on DJIA Stocks
        url: blogs/risk_return
      - image: alcohol.jpg
        subtitle: Analysing Alcohol Patterns
        title: R Work 2 on Alcohol Data
        url: blogs/alcohol
      - image: movies.jpg
        subtitle: Analysing Movies Trends
        title: R Work 3 on IMdb Data
        url: blogs/movies
      - image: pic08.jpg
        subtitle: Good Vibes ONLY
        title: How to make bad vibes good vibes?
        url: blogs/vibe
      - image: pic09.jpeg
        subtitle: A familiarity in disapproval
        title: Was their house their home?
        url: blogs/thehouse
      - image: pic07.jpg
        subtitle: what it means to encourage a culture of giving
        title: Is it still charity if you brag about it?
        url: blogs/charity
  two:
    buttonText: Get To Know Vrinda
    enable: yes
    subtitle: "Vrinda is a student of Finance at London Business School. She was 
      \r\n    born and brought up in a small north-Indian town named Saharanpur. \r\n   
      In her free time, Vrinda likes writing creating nonfiction."
    title: About the Author
    url: blogs/more_about_the_author
